// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <header className="bg-gray-800 text-white p-4">Header</header>
//         <main className="p-6">{children}</main>
//         <footer className="bg-gray-200 text-center p-4">footer</footer>
//       </body>
//     </html>
//   );
// }


// import Sidebar from "@/components/Sidebar";

// function App() {
//   return (
//     <div className="flex">
//       <Sidebar />
//       <main className="flex-1 p-6">
//         <h1>Main Content</h1>
//       </main>
//     </div>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        {/* 🧭 Sidebar хэсэг */}
        <Sidebar />

        {/* 📄 Үндсэн хэсэг */}
        <div className="flex-1">
          <header className="bg-gray-800 text-white p-4">Header</header>
          <main className="p-6">{children}</main>
          <footer className="bg-gray-200 text-center p-4">Footer</footer>
        </div>
      </body>
    </html>
  );
}
