export const aimagImages = {
  "0":  require('@/assets/zurag/0.jpg'),
  "1":  require('@/assets/zurag/1.jpg'),
  "2":  require('@/assets/zurag/2.jpg'),
  "3":  require('@/assets/zurag/3.jpg'),
  "4":  require('@/assets/zurag/4.jpg'),
  "5":  require('@/assets/zurag/5.jpg'),
  "6":  require('@/assets/zurag/6.jpg'),
  "7":  require('@/assets/zurag/7.jpg'),
  "8":  require('@/assets/zurag/govi-altai.jpg'),
  "9":  require('@/assets/zurag/govisumber.jpg'),
  "10": require('@/assets/zurag/khentii.jpg'),
  "11": require('@/assets/zurag/khovd.jpg'),
  "12": require('@/assets/zurag/khuvsgul.jpg'),
  "13": require('@/assets/zurag/orkhon.jpg'),
  "14": require('@/assets/zurag/omnogovi.jpg'),
  "15": require('@/assets/zurag/sukhbaatar.jpg'),
  "16": require('@/assets/zurag/selenge.jpg'),
  "17": require('@/assets/zurag/tov.jpg'),
  "18": require('@/assets/zurag/uvurkhangai.jpg'),
  "19": require('@/assets/zurag/uvs.jpg'),
  "20": require('@/assets/zurag/zavkhan.jpg')
};
