export const aimagImages = {
  "1": require("@/assets/zurag/0.png"),
  "2": require("@/assets/zurag/1.png"),
  "3": require("@/assets/zurag/2.png"),
  "4": require("@/assets/zurag/3.png"),
  "5": require("@/assets/zurag/4.png"),
  "6": require("@/assets/zurag/5.png"),
  "7": require("@/assets/zurag/6.png"),
  "8": require("@/assets/zurag/7.png"),
  "9": require("@/assets/zurag/8.png"),
  "10": require("@/assets/zurag/9.png"),
  "11": require("@/assets/zurag/10.png"),
  "12": require("@/assets/zurag/11.png"),
  "13": require("@/assets/zurag/12.png"),
  "14": require("@/assets/zurag/13.png"),
  "15": require("@/assets/zurag/14.png"),
  "16": require("@/assets/zurag/15.png"),
  "17": require("@/assets/zurag/16.png"),
  "18": require("@/assets/zurag/17.png"),
  "19": require("@/assets/zurag/18.png"),
  "20": require("@/assets/zurag/19.png"),
  "21": require("@/assets/zurag/20.png"),
};
