export const aimagImages = {
  "0":  require('@/assets/zurag/0.png'),
  "1":  require('@/assets/zurag/1.png'),
  "2":  require('@/assets/zurag/2.png'),
  "3":  require('@/assets/zurag/3.png'),
  "4":  require('@/assets/zurag/4.png'),
  "5":  require('@/assets/zurag/5.png'),
  "6":  require('@/assets/zurag/6.png'),
  "7":  require('@/assets/zurag/7.png'),
  // "8":  require('@/assets/zurag/govi-altai.png'),
  // "9":  require('@/assets/zurag/govisumber.png'),
  // "10": require('@/assets/zurag/khentii.png'),
  // "11": require('@/assets/zurag/khovd.png'),
  // "12": require('@/assets/zurag/khuvsgul.png'),
  // "13": require('@/assets/zurag/orkhon.png'),
  // "14": require('@/assets/zurag/omnogovi.png'),
  // "15": require('@/assets/zurag/sukhbaatar.png'),
  // "16": require('@/assets/zurag/selenge.png'),
  // "17": require('@/assets/zurag/tov.png'),
  // "18": require('@/assets/zurag/uvurkhangai.png'),
  // "19": require('@/assets/zurag/uvs.png'),
  // "20": require('@/assets/zurag/zavkhan.png')
};
